version: '3'

dotenv: ['.env']

tasks:
  validateEnv:
    internal: true
    preconditions:
      - test -f .env

  cert:
    desc: "Create CA for internal dev clusters and import in OS X keychain"
    vars:
      certFolder:
        sh: realpath {{ .CERT_FOLDER | trimSuffix "/" }}
      certTld: "{{ .TLD | trimAll \".\" }}"
      certFileBaseName: "{{ .certFolder}}/{{ .certTld }}-ca"
    env:
      CERT_TLD_TRIMMED: "{{ .certTld }}"
    cmds:
      - task: validateEnv
      - mkdir -p {{ .certFolder }}
      - openssl ecparam -name prime256v1 -genkey -noout -out {{ .certFileBaseName }}.key
      - openssl req -new -key {{ .certFileBaseName }}.key -out {{ .certFileBaseName }}.csr -config ca.ini
      - openssl x509 -req -in {{ .certFileBaseName }}.csr -signkey {{ .certFileBaseName }}.key -out {{ .certFileBaseName }}.crt -days 3650 -extfile ca.ini -extensions v3_req
      - openssl x509 -noout -text -in {{ .certFileBaseName }}.crt
      - cmd: sudo security add-trusted-cert -d -r trustRoot -k /Library/Keychains/System.keychain {{ .certFileBaseName }}.crt
        platforms: [darwin]
    preconditions:
      - command -v openssl
    status:
      - test -f {{ .certFileBaseName }}.key
      - test -f {{ .certFileBaseName }}.csr
      - test -f {{ .certFileBaseName }}.crt
    # https://github.com/go-task/task/issues/1945
    # generates:
    #  - "{{ .certFileBaseName }}.crt"
    #  - "{{ .certFileBaseName }}.key"

  dnsmasq-brew-install:
    desc: "Install dnsmasq using Homebrew"
    cmds:
      - brew install dnsmasq
      - sudo brew services start dnsmasq
    status:
      - brew list dnsmasq
      - brew services list | grep dnsmasq
    preconditions:
      - command -v brew

  dnsmasq-brew-configure:
    desc: "Configure dnsmasq that is installed using Homebrew"
    vars:
      certTld: "{{ .TLD | trimAll \".\" }}"
    cmds:
      - task: validateEnv
      - |
        CONFIG_FILE=$(brew --prefix)/etc/dnsmasq.conf
        if ! grep -q "^conf-dir=$(brew --prefix)/etc/dnsmasq.d/,\*\.conf" $CONFIG_FILE; then
          echo "conf-dir=$(brew --prefix)/etc/dnsmasq.d/,*.conf" >> $CONFIG_FILE;
        else
          echo "$CONFIG_FILE was already configured"
        fi
      - mkdir -p $(brew --prefix)/etc/dnsmasq.d
      - echo "address=/{{ .certTld }}/127.0.0.1" > $(brew --prefix)/etc/dnsmasq.d/{{ .certTld }}.conf
      - sudo brew services restart dnsmasq
    preconditions:
      - command -v brew
      - command -v dnsmasq

  dnsmasq-brew:
    desc: "Install and configure dnsmasq using Homebrew"
    cmds:
      - task: dnsmasq-brew-install
      - task: dnsmasq-brew-configure

  k3d-cluster-setup-*:
    desc: "Setup a k3d cluster with port mappings"
    vars:
      clusterNumber: '{{index .MATCH 0 | int}}'
      clusterName: "{{ .K3D_CLUSTER_NAME_PREFIX }}{{ .clusterNumber }}"
      portVarString: "{{ (add .K3D_PORT_START .clusterNumber) | printf \"%2d\" }}"
      portHttp: "{{ .K3D_PORT_PREFIX_HTTP }}{{ .portVarString }}{{ .K3D_PORT_SUFFIX_HTTP }}"
      portHttps: "{{ .K3D_PORT_PREFIX_HTTPS }}{{ .portVarString }}{{ .K3D_PORT_SUFFIX_HTTPS }}"
      kubeConfigFolder: "{{ .K3D_KUBECONFIG_TARGET_DIR | trimSuffix \"/\" }}"
    cmds:
      - |
        k3d cluster create \
        -p "{{ .portHttp }}:80@loadbalancer" \
        -p "{{ .portHttps }}:443@loadbalancer" \
        --kubeconfig-update-default=false \
        {{ .clusterName }} {{.CLI_ARGS}}
      - mkdir -p {{ .kubeConfigFolder }}
      - k3d kubeconfig merge {{ .clusterName }} -o {{ .kubeConfigFolder }}/{{ .clusterName }}
    status:
      - k3d cluster list {{ .clusterName}}
    preconditions:
      - command -v k3d

  k3d-cluster-configure-*:
    desc: "Configure a previously setup k3d cluster"
    vars:
      clusterNumber: '{{index .MATCH 0 | int}}'
      clusterName: "{{ .K3D_CLUSTER_NAME_PREFIX }}{{ .clusterNumber }}"
      certFolder:
        sh: realpath {{ .CERT_FOLDER | trimSuffix "/" }}
      certTld: "{{ .TLD | trimAll \".\" }}"
      certFileBaseName: "{{ .certFolder }}/{{ .certTld }}-ca"
      certManagerNamespace: cert-manager
      certManagerCaName: root-ca
    cmds:
      # Install cert-manager
      - helm repo add jetstack https://charts.jetstack.io
      - helm repo update
      - |
        helm upgrade --install \
          cert-manager jetstack/cert-manager \
          --namespace {{ .certManagerNamespace }} \
          --create-namespace \
          --set crds.enabled=true \
          --set webhook.featureGates="NameConstraints=true" \
          --set featureGates="NameConstraints=true"
      # Set up root CA
      - kubectl -n {{ .certManagerNamespace }} create secret tls {{ .certManagerCaName }} --cert={{ .certFileBaseName }}.crt --key={{ .certFileBaseName }}.key
      - |
        cat <<EOF | kubectl apply -f -
        apiVersion: cert-manager.io/v1
        kind: ClusterIssuer
        metadata:
          name: {{ .certManagerCaName }}
        spec:
          ca:
            secretName: {{ .certManagerCaName }}
        EOF
      # Set up service for east-west traffic

      # Enable Traefik access logging
      - |
        cat <<EOF | kubectl apply -f -
        apiVersion: helm.cattle.io/v1
        kind: HelmChartConfig
        metadata:
          name: traefik
          namespace: kube-system
        spec:
          # See: https://github.com/traefik/traefik-helm-chart/blob/master/traefik/values.yaml
          valuesContent: |-
            logs:
              access:
                enabled: true
        EOF
    preconditions:
      - command -v k3d
      - command -v helm
      - '[[ "$(kubectl config current-context)" == "k3d-{{ .clusterName }}" ]]'
      - k3d cluster list {{ .clusterName}}
